name: "Prepare test"
description: Performs some preparation to run tests
inputs:
  ADMIN_PAT:
    description: ADMIN_PAT
    required: true
  AWS_ACCESS_KEY_ID:
    description: AWS_ACCESS_KEY_ID
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: AWS_SECRET_ACCESS_KEY
    required: true
  AWS_REGISTRY:
    description: AWS_REGISTRY
    required: true
  VERSION_TAG:
    description: VERSION_TAG
    required: false
  REPOSITORY:
    description: REPOSITORY
    required: false
runs:
  using: composite
  steps:
    - name: Debug
      run: echo "${{ github.repository }}/${{ github.ref_name }}"
      shell: bash
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ github.ref_name == 'master' && inputs.ADMIN_PAT || github.token }}
        persist-credentials: ${{ github.ref_name == 'master' }}
        fetch-depth: 1
        ref: ${{ inputs.VERSION_TAG }}
        repository: ${{ inputs.REPOSITORY }}
    - name: Git Config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
      shell: bash
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.15
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Configure NPM registry
      run: npm config set '@circle9r:registry' 'https://npm.pkg.github.com/'
      shell: bash
    - name: Configure NPM registry
      run: npm config set '//npm.pkg.github.com/:_authToken' ${{ inputs.ADMIN_PAT }}
      shell: bash
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ inputs.AWS_REGISTRY }}
